-- migration_fix.sql (v3 - CLEAN, không DO block, không trùng constraint)
-- Chạy file này SAU khi đã tạo bảng sites (bước 1)

-- ===== PROPERTIES =====
CREATE TABLE IF NOT EXISTS properties (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id uuid,
  legacy_id text,
  title text NOT NULL DEFAULT '',
  description text,
  price numeric,
  formatted_price text,
  area numeric,
  formatted_area text,
  frontage text,
  location text,
  coordinates jsonb DEFAULT '{"lat": 11.424, "lng": 106.5962}'::jsonb,
  type text NOT NULL DEFAULT 'Đất nền',
  status text DEFAULT 'Đang bán',
  is_featured boolean DEFAULT false,
  thumbnail_url text,
  images text[] DEFAULT '{}',
  legal_status text,
  legal_images text[] DEFAULT '{}',
  video_url text,
  road_width text,
  tags text[] DEFAULT '{}',
  posted_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE properties ADD COLUMN IF NOT EXISTS site_id uuid;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS legacy_id text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS formatted_price text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS formatted_area text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS frontage text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS legal_status text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS legal_images text[] DEFAULT '{}';

ALTER TABLE properties ADD COLUMN IF NOT EXISTS video_url text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS road_width text;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS tags text[] DEFAULT '{}';

-- ===== SETTINGS =====
CREATE TABLE IF NOT EXISTS settings (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_title text NOT NULL DEFAULT 'BĐS Chơn Thành'
);

ALTER TABLE settings ADD COLUMN IF NOT EXISTS site_id uuid;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_title text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_subtitle text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS banner_url text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS phone text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS zalo text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS email text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS address text;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS footer_text text;

ALTER TABLE settings
ADD COLUMN IF NOT EXISTS search_prefix text DEFAULT 'Chơn Thành, Bình Phước';

-- ===== LEADS =====
CREATE TABLE IF NOT EXISTS leads (
    id uuid DEFAULT gen_random_uuid () PRIMARY KEY,
    site_id uuid,
    customer_name text NOT NULL DEFAULT 'Khách hàng',
    phone text NOT NULL,
    message text,
    property_id uuid,
    source text,
    admin_note text,
    is_read boolean DEFAULT false,
    created_at timestamp
    with
        time zone DEFAULT now() NOT NULL
);

ALTER TABLE leads ADD COLUMN IF NOT EXISTS site_id uuid;

ALTER TABLE leads ADD COLUMN IF NOT EXISTS admin_note text;

ALTER TABLE leads ADD COLUMN IF NOT EXISTS property_id uuid;

-- ===== NEWS_ARTICLES =====
CREATE TABLE IF NOT EXISTS news_articles (
    id uuid DEFAULT gen_random_uuid () PRIMARY KEY,
    site_id uuid,
    title text NOT NULL DEFAULT '',
    excerpt text,
    content text,
    category text DEFAULT 'Tin tức',
    image_url text,
    is_published boolean DEFAULT true,
    published_at timestamp
    with
        time zone DEFAULT now() NOT NULL,
        created_at timestamp
    with
        time zone DEFAULT now() NOT NULL
);

ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS site_id uuid;

-- ===== SEED =====
INSERT INTO
    settings (site_title)
SELECT 'BĐS Chơn Thành'
WHERE
    NOT EXISTS (
        SELECT 1
        FROM settings
        LIMIT 1
    );

-- ===== RLS =====
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;

ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

ALTER TABLE news_articles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cho phép xem Website công khai" ON sites;

DROP POLICY IF EXISTS "Cho phép xem BĐS công khai" ON properties;

DROP POLICY IF EXISTS "Cho phép xem Cài đặt công khai" ON settings;

DROP POLICY IF EXISTS "Cho phép khách gửi SĐT" ON leads;

DROP POLICY IF EXISTS "Cho phép xem Tin tức công khai" ON news_articles;

DROP POLICY IF EXISTS "Admin quản lý Website" ON sites;

DROP POLICY IF EXISTS "Admin quản lý BĐS" ON properties;

DROP POLICY IF EXISTS "Admin quản lý Cấu hình" ON settings;

DROP POLICY IF EXISTS "Admin quản lý Khách hàng" ON leads;

DROP POLICY IF EXISTS "Admin quản lý Tin tức" ON news_articles;

CREATE POLICY "Cho phép xem Website công khai" ON sites FOR
SELECT USING (true);

CREATE POLICY "Cho phép xem BĐS công khai" ON properties FOR
SELECT USING (true);

CREATE POLICY "Cho phép xem Cài đặt công khai" ON settings FOR
SELECT USING (true);

CREATE POLICY "Cho phép khách gửi SĐT" ON leads FOR
INSERT
WITH
    CHECK (true);

CREATE POLICY "Cho phép xem Tin tức công khai" ON news_articles FOR
SELECT USING (is_published = true);

CREATE POLICY "Admin quản lý Website" ON sites FOR ALL TO authenticated USING (true);

CREATE POLICY "Admin quản lý BĐS" ON properties FOR ALL TO authenticated USING (true);

CREATE POLICY "Admin quản lý Cấu hình" ON settings FOR ALL TO authenticated USING (true);

CREATE POLICY "Admin quản lý Khách hàng" ON leads FOR ALL TO authenticated USING (true);

CREATE POLICY "Admin quản lý Tin tức" ON news_articles FOR ALL TO authenticated USING (true);

SELECT 'Migration hoàn tất ✅' AS result;