-- schema.sql
-- File này dùng để khởi tạo cấu trúc Database trên Supabase

-- 1. Bảng quản lý nhiều website/FE dùng chung backend
CREATE TABLE IF NOT EXISTS sites (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_key text UNIQUE NOT NULL,
  name text NOT NULL,
  domain text UNIQUE,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Bảng lưu trữ Thông tin Bất động sản
CREATE TABLE IF NOT EXISTS properties (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id uuid REFERENCES sites(id) ON DELETE CASCADE,
  legacy_id text UNIQUE,
  title text NOT NULL,
  description text,
  price numeric,
  formatted_price text,
  area numeric,
  formatted_area text,
  frontage text,
  location text,
  coordinates jsonb DEFAULT '{"lat": 11.424, "lng": 106.5962}'::jsonb,
  type text NOT NULL,
  status text DEFAULT 'Đang bán',
  is_featured boolean DEFAULT false,
  thumbnail_url text,
  images text[] DEFAULT '{}',
  legal_status text,
  legal_images text[] DEFAULT '{}',
  video_url text,
  road_width text,
  tags text[] DEFAULT '{}',
  posted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Bảng lưu trữ Cấu hình Website
CREATE TABLE IF NOT EXISTS settings (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id uuid REFERENCES sites(id) ON DELETE CASCADE UNIQUE,
  site_title text NOT NULL,
  hero_title text,
  hero_subtitle text,
  banner_url text,
  phone text,
  zalo text,
  email text,
  address text,
  footer_text text,
  search_prefix text DEFAULT 'Chơn Thành, Bình Phước'
);

-- 4. Bảng lưu trữ Khách hàng (Leads)
CREATE TABLE IF NOT EXISTS leads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id uuid REFERENCES sites(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  phone text NOT NULL,
  message text,
  property_id uuid REFERENCES properties(id) ON DELETE SET NULL,
  source text,
  admin_note text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed website mặc định cho các dữ liệu cũ
INSERT INTO sites (site_key, name, is_default)
VALUES ('default', 'BĐS Chơn Thành', true)
ON CONFLICT (site_key) DO NOTHING;

INSERT INTO settings (site_id, site_title)
SELECT id, 'BĐS Chơn Thành'
FROM sites
WHERE site_key = 'default'
ON CONFLICT (site_id) DO NOTHING;

-- 5. BẢO MẬT (RLS)
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Xóa các chính sách cũ nếu có để tránh lỗi khi chạy lại
DROP POLICY IF EXISTS "Cho phép xem Website công khai" ON sites;
DROP POLICY IF EXISTS "Cho phép xem BĐS công khai" ON properties;
DROP POLICY IF EXISTS "Cho phép xem Cài đặt công khai" ON settings;
DROP POLICY IF EXISTS "Cho phép khách gửi SĐT" ON leads;
DROP POLICY IF EXISTS "Admin quản lý Website" ON sites;
DROP POLICY IF EXISTS "Admin quản lý BĐS" ON properties;
DROP POLICY IF EXISTS "Admin quản lý Cấu hình" ON settings;
DROP POLICY IF EXISTS "Admin quản lý Khách hàng" ON leads;

-- Thiết lập chính sách mới
CREATE POLICY "Cho phép xem Website công khai" ON sites FOR SELECT USING (true);
CREATE POLICY "Cho phép xem BĐS công khai" ON properties FOR SELECT USING (true);
CREATE POLICY "Cho phép xem Cài đặt công khai" ON settings FOR SELECT USING (true);
CREATE POLICY "Cho phép khách gửi SĐT" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin quản lý Website" ON sites FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin quản lý BĐS" ON properties FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin quản lý Cấu hình" ON settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin quản lý Khách hàng" ON leads FOR ALL TO authenticated USING (true);
