// mockData.js
// Dữ liệu mẫu cho dự án BĐS Chơn Thành
// Tất cả UI component phải nhận data qua props, KHÔNG hardcode trực tiếp trong component

// --- Hằng số ảnh placeholder (tránh lặp URL) ---
const PLACEHOLDER_IMAGES = [
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=90",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1600&q=90",
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1600&q=90",
];

const PLACEHOLDER_FALLBACK = "/assets/placeholder-land.jpg";

// --- Chi tiết BĐS chính (dùng cho trang Detail) ---
export const mockPropertyData = {
  id: "bds-001",
  title: "Đất nền trung tâm Chơn Thành, thổ cư 100%",
  slug: "dat-nen-trung-tam-chon-thanh-tho-cu-100",
  price: 1200000000,
  formattedPrice: "1.2 Tỷ",
  pricePerM2: 8000000,
  formattedPricePerM2: "8 Triệu/m²",
  area: 150,
  formattedArea: "150 m²",
  dimensions: "5m x 30m",
  frontage: "5m",
  roadWidth: "12m (Nhựa)",
  direction: "Đông Nam",
  legalStatus: "Sổ hồng riêng",
  planningStatus: "Đất ở tại đô thị (ODT)",
  landUse: "Thổ cư 100%",
  description:
    "Vị trí đắc địa ngay trung tâm thị xã Chơn Thành, cách KCN Becamex Chơn Thành chỉ 2km, phù hợp xây nhà trọ, nhà ở hoặc đầu tư sinh lời dài hạn. Khu dân cư hiện hữu đông đúc, hạ tầng hoàn chỉnh, điện nước đầy đủ.",
  longDescription:
    "Đây là lô đất vàng hiếm có tại trung tâm thị xã Chơn Thành – trái tim của vùng kinh tế trọng điểm phía Nam tỉnh Bình Phước. Với mặt tiền 5m tiếp giáp đường nhựa rộng 12m, lô đất lý tưởng để:\n- Xây nhà trọ cho công nhân KCN (nhu cầu thuê rất cao)\n- Xây nhà ở căn hộ mini\n- Đầu tư chờ tăng giá (khu vực tăng 15-20%/năm)\nPháp lý hoàn chỉnh, sổ hồng riêng, sang tên nhanh chóng.",
  images: [
    PLACEHOLDER_IMAGES[0],
    PLACEHOLDER_IMAGES[1],
    PLACEHOLDER_IMAGES[2],
  ],
  thumbnail: PLACEHOLDER_IMAGES[0],
  fallbackImage: PLACEHOLDER_FALLBACK,
  videoUrl: null, // Chưa có video – component phải kiểm tra null trước khi render
  tourUrl: null,  // Chưa có 3D Tour
  amenities: [
    { name: "Chợ Chơn Thành", distance: "500m", icon: "store" },
    { name: "KCN Becamex Chơn Thành", distance: "2km", icon: "factory" },
    { name: "Trường THPT Chơn Thành", distance: "800m", icon: "school" },
    { name: "Bệnh viện Đa khoa Chơn Thành", distance: "1.2km", icon: "hospital" },
    { name: "UBND thị xã Chơn Thành", distance: "700m", icon: "building" },
    { name: "Quốc lộ 13", distance: "300m", icon: "road" },
  ],
  utilities: ["Điện 3 pha", "Nước máy thành phố", "Internet cáp quang", "Camera an ninh"],
  contact: {
    name: "Anh Thanh (Chủ đất)",
    phone: "0901234567",
    zalo: "0901234567",
    avatar: PLACEHOLDER_FALLBACK,
  },
  coordinates: { lat: 11.4240, lng: 106.5962 },
  location: {
    address: "Khu phố 4, Phường Thành Tâm, Thị xã Chơn Thành, Bình Phước",
    ward: "Phường Thành Tâm",
    district: "Thị xã Chơn Thành",
    province: "Bình Phước",
    lat: 11.4240,
    lng: 106.5962,
    mapEmbedUrl:
      "https://maps.google.com/maps?q=11.4240,106.5962&z=15&output=embed",
  },
  postedAt: "2026-03-20",
  updatedAt: "2026-03-25",
  views: 312,
  isFeatured: true,
  status: "Đang bán",
  type: "Đất nền",
  tags: ["Mặt tiền", "Sổ hồng", "Gần KCN", "Thổ cư 100%"],
};

// --- Danh sách 6 BĐS cho trang Homepage ---
export const mockPropertyList = [
  {
    id: "bds-001",
    title: "Đất nền trung tâm Chơn Thành, thổ cư 100%",
    price: 1200000000,
    formattedPrice: "1.2 Tỷ",
    area: 150,
    formattedArea: "150 m²",
    frontage: "5m",
    legalStatus: "Sổ hồng riêng",
    thumbnail: PLACEHOLDER_IMAGES[0],
    images: [PLACEHOLDER_IMAGES[0], PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[2]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Phường Thành Tâm, Chơn Thành",
    coordinates: { lat: 11.4240, lng: 106.5962 },
    type: "Đất nền",
    isFeatured: true,
    status: "Đang bán",
    tags: ["Mặt tiền", "Sổ hồng"],
    postedAt: "2026-03-20",
  },
  {
    id: "bds-002",
    title: "Đất vườn 500m², cách QL13 chỉ 200m, đường xe tải",
    price: 850000000,
    formattedPrice: "850 Triệu",
    area: 500,
    formattedArea: "500 m²",
    frontage: "10m",
    legalStatus: "Sổ đỏ",
    thumbnail: PLACEHOLDER_IMAGES[1],
    images: [PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[0], PLACEHOLDER_IMAGES[2]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Xã Minh Thành, Chơn Thành",
    coordinates: { lat: 11.4180, lng: 106.5880 },
    type: "Đất vườn",
    isFeatured: false,
    status: "Đang bán",
    tags: ["Đường xe tải", "Gần QL13"],
    postedAt: "2026-03-18",
  },
  {
    id: "bds-003",
    title: "Nhà cấp 4 hoàn thiện, hẻm nhựa 6m, KDC hiện hữu",
    price: 650000000,
    formattedPrice: "650 Triệu",
    area: 80,
    formattedArea: "80 m²",
    frontage: "4m",
    legalStatus: "Sổ hồng riêng",
    thumbnail: PLACEHOLDER_IMAGES[2],
    images: [PLACEHOLDER_IMAGES[2], PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[0]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Phường Hưng Long, Chơn Thành",
    coordinates: { lat: 11.4260, lng: 106.6010 },
    type: "Nhà ở",
    isFeatured: false,
    status: "Đang bán",
    tags: ["Nhà hoàn thiện", "Hẻm nhựa"],
    postedAt: "2026-03-15",
  },
  {
    id: "bds-004",
    title: "Lô góc 2 mặt tiền, đối diện KCN Becamex, sinh lời cao",
    price: 2500000000,
    formattedPrice: "2.5 Tỷ",
    area: 200,
    formattedArea: "200 m²",
    frontage: "8m",
    legalStatus: "Sổ hồng riêng",
    thumbnail: PLACEHOLDER_IMAGES[0],
    images: [PLACEHOLDER_IMAGES[0], PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[2]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Phường Minh Đức, Chơn Thành",
    coordinates: { lat: 11.4300, lng: 106.6080 },
    type: "Đất nền",
    isFeatured: true,
    status: "Đang bán",
    tags: ["Lô góc", "2 mặt tiền", "Đối diện KCN"],
    postedAt: "2026-03-22",
  },
  {
    id: "bds-005",
    title: "Đất nền khu dân cư Đồng Xoài mở rộng, sổ hồng sẵn",
    price: 980000000,
    formattedPrice: "980 Triệu",
    area: 120,
    formattedArea: "120 m²",
    frontage: "6m",
    legalStatus: "Sổ hồng riêng",
    thumbnail: PLACEHOLDER_IMAGES[1],
    images: [PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[0], PLACEHOLDER_IMAGES[2]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Phường Tân Bình, Chơn Thành",
    coordinates: { lat: 11.4195, lng: 106.5940 },
    type: "Đất nền",
    isFeatured: false,
    status: "Đang bán",
    tags: ["Sổ hồng sẵn", "KDC quy hoạch"],
    postedAt: "2026-03-10",
  },
  {
    id: "bds-006",
    title: "Nhà phố thương mại mặt tiền đường Hùng Vương, vị trí kinh doanh",
    price: 3800000000,
    formattedPrice: "3.8 Tỷ",
    area: 180,
    formattedArea: "180 m²",
    frontage: "7m",
    legalStatus: "Sổ hồng riêng",
    thumbnail: PLACEHOLDER_IMAGES[2],
    images: [PLACEHOLDER_IMAGES[2], PLACEHOLDER_IMAGES[1], PLACEHOLDER_IMAGES[0]],
    fallbackImage: PLACEHOLDER_FALLBACK,
    location: "Đường Hùng Vương, Chơn Thành",
    coordinates: { lat: 11.4225, lng: 106.5975 },
    type: "Nhà phố",
    isFeatured: true,
    status: "Đang bán",
    tags: ["Mặt tiền đẹp", "Kinh doanh", "Trung tâm"],
    postedAt: "2026-03-25",
  },
];

// --- Danh mục loại BĐS (dùng cho filter/tab) ---
export const propertyTypes = [
  { value: "all", label: "Tất cả" },
  { value: "Đất nền", label: "Đất nền" },
  { value: "Đất vườn", label: "Đất vườn" },
  { value: "Nhà ở", label: "Nhà ở" },
  { value: "Nhà phố", label: "Nhà phố" },
];

// --- Khoảng giá filter ---
export const priceRanges = [
  { value: "all", label: "Tất cả mức giá" },
  { value: "under-1ty", label: "Dưới 1 Tỷ", min: 0, max: 1000000000 },
  { value: "1ty-2ty", label: "1 - 2 Tỷ", min: 1000000000, max: 2000000000 },
  { value: "2ty-5ty", label: "2 - 5 Tỷ", min: 2000000000, max: 5000000000 },
  { value: "over-5ty", label: "Trên 5 Tỷ", min: 5000000000, max: Infinity },
];
